Cache:
  ## the cachePath key, if set, will override 'cachePath' within the individual module options below
  #cachePath: ".cache"
  defaultModule: "cache_fs"
  options:
    workers: 2
    processor:
      putWhitelist: ["10.211.8.11", "10.210.7.21", "10.210.7.20", "10.210.7.29", # van-test04-win, as7, as8, as9 (to allow mirroring e.g. as8-->as7
        "10.211.13.236","10.210.0.61","10.210.0.62","10.210.0.63","10.210.0.64","10.211.13.165","10.211.13.166","10.211.13.167","10.211.13.168","10.211.237", #van-build6x
        "10.211.13.170","10.211.13.171","10.211.13.172","10.211.13.173","10.211.13.174","10.211.13.175","10.211.13.176","10.211.13.177","10.211.238","10.211.239", #van-build7x
        "10.211.13.190","10.211.13.191","10.211.13.192","10.211.13.193","10.211.13.194","10.211.13.195","10.211.13.196","10.211.13.197","10.210.1.98","10.210.1.99"] #van-build9x
    cache_ram:
      cachePath: ".cache_ram"
      pageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
    cache_fs:
      cachePath: "/data/cache60_fs"
      cleanupOptions:
        expireTimeSpan: "P90D"
        maxCacheSize: 429496729600 # 400GB
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
Mirror:
  addresses: []
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000
Server:
  port: 8126
  options:
    allowIpv6: false
Global:
  logLevel: 4
Diagnostics:
  clientRecorder: false
  clientRecorderOptions:
    bufferSize: 10000000
    saveDir: "diagnostics/client-recordings"
