Cache:
  ## the cachePath key, if set, will override 'cachePath' within the individual module options below
  #cachePath: ".cache"
  defaultModule: "cache_fs"
  options:
    workers: 2
    processor:
      putWhitelist: ["10.211.0.214","10.211.1.18","10.210.0.60","10.210.0.61","10.210.0.62","10.210.0.63","10.210.0.64","10.210.0.65","10.210.0.66","10.210.0.67","10.210.0.68","10.210.0.69",      "10.210.0.70","10.210.0.71","10.210.0.72","10.210.0.73","10.210.0.74","10.210.0.75","10.210.0.76","10.210.0.77","10.210.0.78","10.210.0.79",      "10.210.0.90","10.210.0.91","10.210.0.92","10.210.0.93","10.210.0.94","10.210.0.95","10.210.0.96","10.210.0.97"]
    cache_ram:
      cachePath: ".cache_ram"
      pageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
    cache_fs:
      cachePath: "/data/cache60_fs"
      cleanupOptions:
        expireTimeSpan: "P90D"
        maxCacheSize: 91268055040
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
Mirror:
  addresses: []
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000
Server:
  port: 8126
  options:
    allowIpv6: false
Global:
  logLevel: 5
Diagnostics:
  clientRecorder: false
  clientRecorderOptions:
    bufferSize: 10000000
    saveDir: "diagnostics/client-recordings"