Cache:
  defaultModule: "cache_fs"
  options:
    processor:
      putWhitelist: []
    cache_ram:
      cachePath: ".cache_ram"
      pageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
    cache_fs:
      cachePath: ".cache_fs"
      cleanupOptions:
        expireTimeSpan: "P30D"
        maxCacheSize: 0
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
Mirror:
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000
Server:
  options:
    allowIpv6: false