Cache:
  defaultModule: "cache_fs"
  options:
    processor:
      putWhitelist: ["10.210.0.61","10.210.0.62","10.210.0.63","10.210.0.64","10.210.0.70","10.210.0.71","10.210.0.72","10.210.0.73","10.210.0.74","10.210.0.75","10.210.0.76","10.210.0.77"]
    cache_ram:
      cachePath: ".cache_ram"
      pageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
    cache_fs:
      cachePath: "/data/cache5.0"
      cleanupOptions:
        expireTimeSpan: "P30D"
        maxCacheSize: 0
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: false
      highReliabilityOptions:
        reliabilityThreshold: 2
        saveUnreliableVersionArtifacts: true
        multiClient: false
Mirror:
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000
Server:
  options:
    allowIpv6: false